language: java
jdk:
  - oraclejdk8

script:
  - mvn install -B -V
  - mvn javadoc:jar
  - mvn javadoc:test-aggregate

notifications:
  irc: "irc.freenode.org#fcrepo"
  email:
      - ralf.claussnitzer@slub-dresden.de
      - fedora-tech@googlegroups.com

